const ErrosCpf = {
  CPF_VAZIO: "CPF_VAZIO",
  CPF_INVALIDO: "CPF_INVALIDO",
  CPF_PEQUENO: "CPF_TAMANHO_MENOR_11_CARACTERES",
  CPF_GRANDE: "CPF_TAMANHO_MAIOR_11_CARACTERES",
  CPF_1_DV_INVALIDO: "CPF_1_DV_INVALIDO",
  CPF_2_DV_INVALIDO: "CPF_2_DV_INVALIDO"
} as const;

export default ErrosCpf;
